name = "evara-worker"
main = "src/index.ts"
compatibility_date = "2026-03-28"

[[r2_buckets]]
binding = "EVARA_BUCKET"
bucket_name = "evara-documents"

[vars]
META_PHONE_NUMBER_ID = "1126911513833857"
WEBHOOK_VERIFY_TOKEN = "evara-webhook-2026"
